name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install
      run: cargo install moleculec --vers ${MOLC_VERSION}
    - name: install2
      run: cargo install --path .
    - name: Run ci tests
      run: make all
